settings:
  use:
    custom-wildcard-node: false
    material-names: true
    op-perms: true
  notify-player: true
checks:
  blocks:
    break: true
    place: true
    ignite: true
  items:
    use: true
    have: true
    drop: true
    pickup: true
  metadata: true
 
methods:
  item-permissions: click #valid values are [click,pickup,drop]
  item-fullscan: false
  
messages:
  permissions:
    denied: '&4You do not have permission'
    empty: for that!
    full: '&e%1$s %2$s'